#!/usr/bin/env bash
set -e

# Become super user before starting work
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

printf "\nBootstrapping setup up this Mac...\n\n"

# Brew
if ! command -v brew > /dev/null 2>&1; then
  printf "\nInstalling Brew\n"
  CI=1 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew analytics off
fi

# Git the repo
if [ ! -e ~/mac-setup ]; then
  printf "\nCloning Mac setup\n"
  git clone https://github.com/sutch/mac-setup.git ~/mac-setup
fi

bash ~/mac-setup/setup-mac
