#!/usr/bin/env bash
set -e

# Run in mac-setup folder
cd -P "$(dirname "${BASH_SOURCE}")"

# Become super user before starting work
sudo -v

printf "\nSetting up this Mac...\n\n"

# Enable italic support
tic xterm-256color-italic.terminfo

# Brew
if ! command -v brew > /dev/null 2>&1; then
  printf "\nInstalling Brew\n"
  CI=1 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew analytics off
fi

printf "\nUpdating Brew\n"
brew update
brew upgrade
printf "\nInstalling 3rd party Brew taps\n"
comm -23 <(sort tap.txt) <(brew tap) | xargs brew tap
# Update tap.txt
brew tap > tap.txt
printf "\nInstalling Brew taps\n"
comm -23 <(sort brew.txt) <(brew leaves) | xargs brew install
# Update brew.txt
brew leaves > brew.txt
printf "\nInstalling Cask taps\n"
comm -23 <(sort cask.txt) <(brew cask ls) | xargs brew cask install
# Update cask.txt
brew cask ls > cask.txt
brew cleanup

printf "\nMaking zsh the default shell"
if ! grep -q $(which zsh) /etc/shells; then
  sudo sh -c "echo $(which zsh) >> /etc/shells"
fi
sudo chsh -s $(which zsh)

if [ ! -e ~/.oh-my-zsh ]; then
  printf "\nInstalling oh-my-zsh\n"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
else
  printf "\nUpgrading oh-my-zsh\n"
  zsh $ZSH/tools/upgrade.sh
fi

printf "\n\n\nAll good. Enjoy your day, human.\n"
